# Tell ArgoCD where to find the ubiquitous-journey project
source: https://github.com/DarkDragonEl/devopsday-gitops.git
team: prod
release: infra

applications:
  # Tooling to support CI/CD
  - name: prod-infra
    enabled: true
    source_path: "prod-infra"
    helm_values:
      - bootstrap/prod-bootstrap-values.yaml

  - name: dev-stage-infra
    enabled: true
    source_path: "prod-infra"
    helm_values:
      - bootstrap/dev-stage-bootstrap-values.yaml
