apiVersion: v2
appVersion: "v0.0.1"
description: A Helm chart for deploying and managing Openshift projects 🦆
name: projects-infra
version: 1.0.0
home: https://github.com/DarkDragonEl/devopsday-gitops
icon: https://www.iconpacks.net/icons/1/free-rocket-icon-1206-thumb.png
maintainers:
  - name: bguerrer
