---
# name of instances
name: argocd

# this is for argo type deployments of this chart (set to true)
ignoreHelmHooks: false

# add to this list to deploy team instances to these namespaces
namespaces:
- prod-infra
- dev-infra

# operator manages upgrades
operator:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  sourceName: redhat-operators
  sourceNamespace: openshift-marketplace
  disableDefaultArgoCD: true

# see the TEAM_DOCS.md for more information
teamInstancesAreClusterScoped: true

# adding your secrets for git access or other repository credentials
secrets:
  - name: git-auth
    username: 'DarkDragonEl'
    password: ''
    sshPrivateKey: ''

# https://argocd-operator.readthedocs.io/en/latest/reference/argocd/
argocd_cr:
  version: v2.5.12
  applicationSet: {}
  notifications:
    enabled: true
  rbac:
    defaultPolicy: 'role:admin'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
  server:
    route:
      enabled: true
      tls:
        termination: reencrypt
  dex:
    openShiftOAuth: true

  initialRepositories: |
    - name: devopsday-gitops
      url: https://github.com/DarkDragonEl/devopsday-gitops.git
    - name: redhat-cop
      type: helm
      url: https://redhat-cop.github.io/helm-charts

  # configure your repo credential template (override this)
  repositoryCredentials: |
     - url: https://github.com/DarkDragonEl/devopsday-gitops
       type: git
       passwordSecret:
         key: password
         name: git-auth
       usernameSecret:
         key: username
         name: git-auth